apiVersion: v1
kind: Pod
metadata:
  name: nginx-probe
  labels:
    developer: fajrul
    scrum-team: pecel-lele
    description: learning-kubernetes
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3