apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-replica-set
  template:
    metadata:
      name: nginx
      labels:
        name: nginx-replica-set
        developer: fajrul
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    developer: fajrul
  ports:
    - port: 8080
      targetPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    developer: fajrul
spec:
  containers:
    - name: curl
      image: khannedy/nginx-curl